import type { ComponentType } from "react";
import {
  Apresentacao,
  ApresentacaoEmpresas,
  Canais,
  Capa,
  Duelo,
  Nomes,
  IdentificacaoCanais,
  IntroducaoWebsite,
  Percurso,
  Pergunta,
  Radar6,
  Redes,
  Website,
  type ChapterProps,
} from "./act1";
import { InesPersona, JornadaCompra, Min0, Min12, Min3, Min8 } from "./act2";
import {
  AnatomiaPublicacao,
  Bastidores,
  Bio,
  Conclusao,
  EmpresaEscolhida,
  Indicadores,
  Jogada,
  Jogadas,
  MarcaX,
  Mercado,
  NoAr,
  OQueVimos,
  OsPosts,
  PorqueSpal,
  Publicacao,
  Resposta,
  Semana,
  SimulacaoReal,
} from "./act3";

export const CHAPTERS: Record<string, ComponentType<ChapterProps>> = {
  capa: Capa,
  apresentacao: Apresentacao,
  "apresentacao-empresas": ApresentacaoEmpresas,
  nomes: Nomes,
  pergunta: Pergunta,
  "identificacao-canais": IdentificacaoCanais,
  canais: Canais,
  "introducao-website": IntroducaoWebsite,
  website: Website,
  "duelo-1": ({ active }) => <Duelo n={1} active={active} />,
  "duelo-2": ({ active }) => <Duelo n={2} active={active} />,
  "duelo-3": ({ active }) => <Duelo n={3} active={active} />,
  "duelo-4": ({ active }) => <Duelo n={4} active={active} />,
  "duelo-5": ({ active }) => <Duelo n={5} active={active} />,
  "duelo-6": ({ active }) => <Duelo n={6} active={active} />,
  percurso: Percurso,
  radar: Radar6,
  redes: Redes,
  "jornada-compra": JornadaCompra,
  ines: InesPersona,
  min0: Min0,
  min3: Min3,
  min8: Min8,
  min12: Min12,
  resumo: OQueVimos,
  "empresa-escolhida": EmpresaEscolhida,
  "porque-spal": PorqueSpal,
  jogadas: Jogadas,
  "jogada-1": ({ active }) => <Jogada n={1} active={active} />,
  "jogada-2": ({ active }) => <Jogada n={2} active={active} />,
  "jogada-3": ({ active }) => <Jogada n={3} active={active} />,
  semana: Semana,
  "os-posts": OsPosts,
  publicacao: Publicacao,
  "anatomia-publicacao": AnatomiaPublicacao,
  bio: Bio,
  resposta: Resposta,
  "no-ar": NoAr,
  marcax: MarcaX,
  "simulacao-real": SimulacaoReal,
  indicadores: Indicadores,
  bastidores: Bastidores,
  mercado: Mercado,
  conclusao: Conclusao,
};
